// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package chat.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the Chat module
	public static chat.proxies.Message createNewMessage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Chat.CreateNewMessage").withParams(params).execute(context);
		return result == null ? null : chat.proxies.Message.initialize(context, result);
	}
	public static void iVK_Send(IContext context, chat.proxies.Message _message, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("Chat.IVK_Send").withParams(params).execute(context);
	}
	public static void microflow1(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("Chat.Microflow1").withParams(params).execute(context);
	}
	public static java.util.List<chat.proxies.Message> microflow1_2(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Chat.Microflow1_2").withParams(params).execute(context);
		java.util.List<chat.proxies.Message> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(chat.proxies.Message.initialize(context, obj));
		}
		return result;
	}
	public static chat.proxies.Message microflow1_2_2(IContext context, administration.proxies.Account _account, chat.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		params.put("Message", _message == null ? null : _message.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Chat.Microflow1_2_2").withParams(params).execute(context);
		return result == null ? null : chat.proxies.Message.initialize(context, result);
	}
	public static java.util.List<chat.proxies.Message> microflow1_2_2_2(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Chat.Microflow1_2_2_2").withParams(params).execute(context);
		java.util.List<chat.proxies.Message> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(chat.proxies.Message.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<administration.proxies.Account> retrieveCurrentUserMessagesAccount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Chat.RetrieveCurrentUserMessagesAccount").withParams(params).execute(context);
		java.util.List<administration.proxies.Account> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(administration.proxies.Account.initialize(context, obj));
		}
		return result;
	}
}