// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imagecreator.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the ImageCreator module
	public static void iVK_ChatGptForImageCreation(IContext context, imagecreator.proxies.Image _image)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("image", _image == null ? null : _image.getMendixObject());
		Core.microflowCall("ImageCreator.IVK_ChatGptForImageCreation").withParams(params).execute(context);
	}
	public static void showImageCreatorOverviewPage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ImageCreator.ShowImageCreatorOverviewPage").withParams(params).execute(context);
	}
}