// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administration.proxies;

public class Account extends system.proxies.User
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Administration.Account";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FullName("FullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		IsClockedIn("IsClockedIn"),
		TotalLeave("TotalLeave"),
		TotalSickLeave("TotalSickLeave"),
		TotalCasualLeave("TotalCasualLeave"),
		TotalMarriageLeave("TotalMarriageLeave"),
		TotalPaternityLeave("TotalPaternityLeave"),
		PrivilegeLeave("PrivilegeLeave"),
		Position("Position"),
		TempDate("TempDate"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Account(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Administration.Account"));
	}

	protected Account(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountMendixObject)
	{
		super(context, accountMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Administration.Account", accountMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Administration.Account");
	}

	/**
	 * @deprecated Use 'Account.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static administration.proxies.Account initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return administration.proxies.Account.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static administration.proxies.Account initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new administration.proxies.Account(context, mendixObject);
	}

	public static administration.proxies.Account load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return administration.proxies.Account.initialize(context, mendixObject);
	}

	public static java.util.List<administration.proxies.Account> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<administration.proxies.Account> result = new java.util.ArrayList<administration.proxies.Account>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Administration.Account" + xpathConstraint))
			result.add(administration.proxies.Account.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FullName
	 */
	public final java.lang.String getFullName()
	{
		return getFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FullName
	 */
	public final java.lang.String getFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullName.toString());
	}

	/**
	 * Set value of FullName
	 * @param fullname
	 */
	public final void setFullName(java.lang.String fullname)
	{
		setFullName(getContext(), fullname);
	}

	/**
	 * Set value of FullName
	 * @param context
	 * @param fullname
	 */
	public final void setFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullname)
	{
		getMendixObject().setValue(context, MemberNames.FullName.toString(), fullname);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of IsLocalUser
	 */
	public final java.lang.Boolean getIsLocalUser()
	{
		return getIsLocalUser(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLocalUser
	 */
	public final java.lang.Boolean getIsLocalUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLocalUser.toString());
	}

	/**
	 * Set value of IsLocalUser
	 * @param islocaluser
	 */
	public final void setIsLocalUser(java.lang.Boolean islocaluser)
	{
		setIsLocalUser(getContext(), islocaluser);
	}

	/**
	 * Set value of IsLocalUser
	 * @param context
	 * @param islocaluser
	 */
	public final void setIsLocalUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean islocaluser)
	{
		getMendixObject().setValue(context, MemberNames.IsLocalUser.toString(), islocaluser);
	}

	/**
	 * @return value of IsClockedIn
	 */
	public final java.lang.Boolean getIsClockedIn()
	{
		return getIsClockedIn(getContext());
	}

	/**
	 * @param context
	 * @return value of IsClockedIn
	 */
	public final java.lang.Boolean getIsClockedIn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsClockedIn.toString());
	}

	/**
	 * Set value of IsClockedIn
	 * @param isclockedin
	 */
	public final void setIsClockedIn(java.lang.Boolean isclockedin)
	{
		setIsClockedIn(getContext(), isclockedin);
	}

	/**
	 * Set value of IsClockedIn
	 * @param context
	 * @param isclockedin
	 */
	public final void setIsClockedIn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isclockedin)
	{
		getMendixObject().setValue(context, MemberNames.IsClockedIn.toString(), isclockedin);
	}

	/**
	 * @return value of TotalLeave
	 */
	public final java.math.BigDecimal getTotalLeave()
	{
		return getTotalLeave(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalLeave
	 */
	public final java.math.BigDecimal getTotalLeave(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalLeave.toString());
	}

	/**
	 * Set value of TotalLeave
	 * @param totalleave
	 */
	public final void setTotalLeave(java.math.BigDecimal totalleave)
	{
		setTotalLeave(getContext(), totalleave);
	}

	/**
	 * Set value of TotalLeave
	 * @param context
	 * @param totalleave
	 */
	public final void setTotalLeave(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalleave)
	{
		getMendixObject().setValue(context, MemberNames.TotalLeave.toString(), totalleave);
	}

	/**
	 * @return value of TotalSickLeave
	 */
	public final java.math.BigDecimal getTotalSickLeave()
	{
		return getTotalSickLeave(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalSickLeave
	 */
	public final java.math.BigDecimal getTotalSickLeave(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalSickLeave.toString());
	}

	/**
	 * Set value of TotalSickLeave
	 * @param totalsickleave
	 */
	public final void setTotalSickLeave(java.math.BigDecimal totalsickleave)
	{
		setTotalSickLeave(getContext(), totalsickleave);
	}

	/**
	 * Set value of TotalSickLeave
	 * @param context
	 * @param totalsickleave
	 */
	public final void setTotalSickLeave(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalsickleave)
	{
		getMendixObject().setValue(context, MemberNames.TotalSickLeave.toString(), totalsickleave);
	}

	/**
	 * @return value of TotalCasualLeave
	 */
	public final java.math.BigDecimal getTotalCasualLeave()
	{
		return getTotalCasualLeave(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCasualLeave
	 */
	public final java.math.BigDecimal getTotalCasualLeave(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalCasualLeave.toString());
	}

	/**
	 * Set value of TotalCasualLeave
	 * @param totalcasualleave
	 */
	public final void setTotalCasualLeave(java.math.BigDecimal totalcasualleave)
	{
		setTotalCasualLeave(getContext(), totalcasualleave);
	}

	/**
	 * Set value of TotalCasualLeave
	 * @param context
	 * @param totalcasualleave
	 */
	public final void setTotalCasualLeave(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalcasualleave)
	{
		getMendixObject().setValue(context, MemberNames.TotalCasualLeave.toString(), totalcasualleave);
	}

	/**
	 * @return value of TotalMarriageLeave
	 */
	public final java.math.BigDecimal getTotalMarriageLeave()
	{
		return getTotalMarriageLeave(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalMarriageLeave
	 */
	public final java.math.BigDecimal getTotalMarriageLeave(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalMarriageLeave.toString());
	}

	/**
	 * Set value of TotalMarriageLeave
	 * @param totalmarriageleave
	 */
	public final void setTotalMarriageLeave(java.math.BigDecimal totalmarriageleave)
	{
		setTotalMarriageLeave(getContext(), totalmarriageleave);
	}

	/**
	 * Set value of TotalMarriageLeave
	 * @param context
	 * @param totalmarriageleave
	 */
	public final void setTotalMarriageLeave(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalmarriageleave)
	{
		getMendixObject().setValue(context, MemberNames.TotalMarriageLeave.toString(), totalmarriageleave);
	}

	/**
	 * @return value of TotalPaternityLeave
	 */
	public final java.math.BigDecimal getTotalPaternityLeave()
	{
		return getTotalPaternityLeave(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalPaternityLeave
	 */
	public final java.math.BigDecimal getTotalPaternityLeave(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalPaternityLeave.toString());
	}

	/**
	 * Set value of TotalPaternityLeave
	 * @param totalpaternityleave
	 */
	public final void setTotalPaternityLeave(java.math.BigDecimal totalpaternityleave)
	{
		setTotalPaternityLeave(getContext(), totalpaternityleave);
	}

	/**
	 * Set value of TotalPaternityLeave
	 * @param context
	 * @param totalpaternityleave
	 */
	public final void setTotalPaternityLeave(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalpaternityleave)
	{
		getMendixObject().setValue(context, MemberNames.TotalPaternityLeave.toString(), totalpaternityleave);
	}

	/**
	 * @return value of PrivilegeLeave
	 */
	public final java.math.BigDecimal getPrivilegeLeave()
	{
		return getPrivilegeLeave(getContext());
	}

	/**
	 * @param context
	 * @return value of PrivilegeLeave
	 */
	public final java.math.BigDecimal getPrivilegeLeave(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.PrivilegeLeave.toString());
	}

	/**
	 * Set value of PrivilegeLeave
	 * @param privilegeleave
	 */
	public final void setPrivilegeLeave(java.math.BigDecimal privilegeleave)
	{
		setPrivilegeLeave(getContext(), privilegeleave);
	}

	/**
	 * Set value of PrivilegeLeave
	 * @param context
	 * @param privilegeleave
	 */
	public final void setPrivilegeLeave(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal privilegeleave)
	{
		getMendixObject().setValue(context, MemberNames.PrivilegeLeave.toString(), privilegeleave);
	}

	/**
	 * @return value of Position
	 */
	public final java.lang.String getPosition()
	{
		return getPosition(getContext());
	}

	/**
	 * @param context
	 * @return value of Position
	 */
	public final java.lang.String getPosition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Position.toString());
	}

	/**
	 * Set value of Position
	 * @param position
	 */
	public final void setPosition(java.lang.String position)
	{
		setPosition(getContext(), position);
	}

	/**
	 * Set value of Position
	 * @param context
	 * @param position
	 */
	public final void setPosition(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String position)
	{
		getMendixObject().setValue(context, MemberNames.Position.toString(), position);
	}

	/**
	 * @return value of TempDate
	 */
	public final java.util.Date getTempDate()
	{
		return getTempDate(getContext());
	}

	/**
	 * @param context
	 * @return value of TempDate
	 */
	public final java.util.Date getTempDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TempDate.toString());
	}

	/**
	 * Set value of TempDate
	 * @param tempdate
	 */
	public final void setTempDate(java.util.Date tempdate)
	{
		setTempDate(getContext(), tempdate);
	}

	/**
	 * Set value of TempDate
	 * @param context
	 * @param tempdate
	 */
	public final void setTempDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date tempdate)
	{
		getMendixObject().setValue(context, MemberNames.TempDate.toString(), tempdate);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final administration.proxies.Account that = (administration.proxies.Account) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Administration.Account";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
