// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package chatbot.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the ChatBot module
	public static chatbot.proxies.Chat createNewChat(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("ChatBot.CreateNewChat").withParams(params).execute(context);
		return result == null ? null : chatbot.proxies.Chat.initialize(context, result);
	}
	public static void iVK_ChatGpt(IContext context, chatbot.proxies.Chat _chat)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Chat", _chat == null ? null : _chat.getMendixObject());
		Core.microflowCall("ChatBot.IVK_ChatGpt").withParams(params).execute(context);
	}
	public static void openChatBot(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ChatBot.OpenChatBot").withParams(params).execute(context);
	}
}