// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imagecreator.proxies;

public class Links
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject linksMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ImageCreator.Links";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ImageLinks("ImageLinks"),
		Links_Image("ImageCreator.Links_Image");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Links(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ImageCreator.Links"));
	}

	protected Links(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject linksMendixObject)
	{
		if (linksMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ImageCreator.Links", linksMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ImageCreator.Links");

		this.linksMendixObject = linksMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Links.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static imagecreator.proxies.Links initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return imagecreator.proxies.Links.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static imagecreator.proxies.Links initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new imagecreator.proxies.Links(context, mendixObject);
	}

	public static imagecreator.proxies.Links load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return imagecreator.proxies.Links.initialize(context, mendixObject);
	}

	public static java.util.List<imagecreator.proxies.Links> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<imagecreator.proxies.Links> result = new java.util.ArrayList<imagecreator.proxies.Links>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ImageCreator.Links" + xpathConstraint))
			result.add(imagecreator.proxies.Links.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ImageLinks
	 */
	public final java.lang.String getImageLinks()
	{
		return getImageLinks(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageLinks
	 */
	public final java.lang.String getImageLinks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageLinks.toString());
	}

	/**
	 * Set value of ImageLinks
	 * @param imagelinks
	 */
	public final void setImageLinks(java.lang.String imagelinks)
	{
		setImageLinks(getContext(), imagelinks);
	}

	/**
	 * Set value of ImageLinks
	 * @param context
	 * @param imagelinks
	 */
	public final void setImageLinks(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imagelinks)
	{
		getMendixObject().setValue(context, MemberNames.ImageLinks.toString(), imagelinks);
	}

	/**
	 * @return value of Links_Image
	 */
	public final imagecreator.proxies.Image getLinks_Image() throws com.mendix.core.CoreException
	{
		return getLinks_Image(getContext());
	}

	/**
	 * @param context
	 * @return value of Links_Image
	 */
	public final imagecreator.proxies.Image getLinks_Image(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		imagecreator.proxies.Image result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Links_Image.toString());
		if (identifier != null)
			result = imagecreator.proxies.Image.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Links_Image
	 * @param links_image
	 */
	public final void setLinks_Image(imagecreator.proxies.Image links_image)
	{
		setLinks_Image(getContext(), links_image);
	}

	/**
	 * Set value of Links_Image
	 * @param context
	 * @param links_image
	 */
	public final void setLinks_Image(com.mendix.systemwideinterfaces.core.IContext context, imagecreator.proxies.Image links_image)
	{
		if (links_image == null)
			getMendixObject().setValue(context, MemberNames.Links_Image.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Links_Image.toString(), links_image.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return linksMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final imagecreator.proxies.Links that = (imagecreator.proxies.Links) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ImageCreator.Links";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
